export const branches = [
  { name: 'Awendo', code: '143' },
  { name: 'Bomet', code: '122' },
  { name: 'Bondo', code: '075' },
  { name: 'Bungoma', code: '048' },
  { name: 'Buruburu', code: '095' },
  { name: 'Busia', code: '078' },
  { name: 'Changamwe', code: '120' },
  { name: 'Chuka', code: '021' },
  { name: 'Community', code: '017' },
  { name: 'Community Supreme', code: '018' },
  { name: 'Daadab', code: '136' },
  { name: 'Dagoretti', code: '169' },
  { name: 'Diaspora Banking', code: '054' },
  { name: 'Donholm', code: '082' },
  { name: 'Eastleigh', code: '084' },
  { name: 'Eldama Ravine', code: '131' },
  { name: 'Eldoret', code: '030' },
  { name: 'Eldoret Market', code: '109' },
  { name: 'Eldoret Supreme', code: '164' },
  { name: 'Emali', code: '181' },
  { name: 'Embakasi', code: '132' },
  { name: 'Embu', code: '019' },
  { name: 'Enterprise Road', code: '080' },
  { name: 'EPZ Athi River', code: '149' },
  { name: 'Equity Centre', code: '081' },
  { name: 'Fourways', code: '002' },
  { name: 'Garden City', code: '175' },
  { name: 'Garissa', code: '058' },
  { name: 'Gatundu', code: '066' },
  { name: 'Gikomba', code: '043' },
  { name: 'Gilgil', code: '077' },
  { name: 'Githunguri', code: '093' },
  { name: 'Githurai', code: '071' },
  { name: 'Harambee', code: '024' },
  { name: 'Hola', code: '121' },
  { name: 'Homabay', code: '098' },
  { name: 'Industrial Area', code: '056' },
  { name: 'Isiolo', code: '041' },
  { name: 'Iten', code: '153' },
  { name: 'JKIA Cargo', code: '148' },
  { name: 'Juja', code: '152' },
  { name: 'Kabarnet', code: '139' },
  { name: 'Kagio', code: '042' },
  { name: 'Kagwe', code: '182' },
  { name: 'Kahawa House', code: '133' },
  { name: 'Kajiado', code: '086' },
  { name: 'Kakamega', code: '050' },
  { name: 'Kakuma', code: '165' },
  { name: 'Kangari', code: '007' },
  { name: 'Kangema', code: '003' },
  { name: 'Kangemi', code: '137' },
  { name: 'Kapenguria', code: '107' },
  { name: 'Kapsabet', code: '049' },
  { name: 'Kapsowar', code: '157' },
  { name: 'Karatina', code: '004' },
  { name: 'Karen', code: '125' },
  { name: 'Karen Supreme Centre', code: '163' },
  { name: 'Kariobangi', code: '032' },
  { name: 'Kasarani', code: '118' },
  { name: 'Kawangware', code: '180' },
  { name: 'Kayole', code: '065' },
  { name: 'Kengeleni', code: '114' },
  { name: 'Kenol', code: '089' },
  { name: 'Kenyatta Avenue', code: '129' },
  { name: 'Kenyatta Avenue Supreme', code: '160' },
  { name: 'Kenyatta University', code: '113' },
  { name: 'Kericho', code: '028' },
  { name: 'Keroka', code: '124' },
  { name: 'Kerugoya', code: '010' },
  { name: 'Kiambu', code: '064' },
  { name: 'Kibera', code: '117' },
  { name: 'Kibwezi', code: '173' },
  { name: 'Kikuyu', code: '057' },
  { name: 'Kilgoris', code: '123' },
  { name: 'Kilifi', code: '106' },
  { name: 'Kilimani', code: '145' },
  { name: 'Kilimani Supreme', code: '147' },
  { name: 'Kimathi', code: '026' },
  { name: 'Kimende', code: '111' },
  { name: 'Kiriaini', code: '005' },
  { name: 'Kiserian', code: '168' },
  { name: 'Kisii', code: '051' },
  { name: 'Kisumu', code: '029' },
  { name: 'Kisumu Angawa', code: '126' },
  { name: 'Kisumu Supreme', code: '170' },
  { name: 'Kitale', code: '033' },
  { name: 'Kitengela', code: '070' },
  { name: 'Kitui', code: '072' },
  { name: 'Knut House', code: '035' },
  { name: 'KPA Sub-Branch', code: '161' },
  { name: 'Kutus', code: '172' },
  { name: 'Kwale', code: '158' },
  { name: 'Lamu', code: '159' },
  { name: 'Lavington Supreme', code: '141' },
  { name: 'Limuru', code: '069' },
  { name: 'Litein', code: '053' },
  { name: 'Lodwar', code: '099' },
  { name: 'Loitokitok', code: '074' },
  { name: 'Machakos', code: '060' },
  { name: 'Malaba', code: '105' },
  { name: 'Malindi', code: '045' },
  { name: 'Mama Ngina', code: '015' },
  { name: 'Mandera', code: '100' },
  { name: 'Maralal', code: '110' },
  { name: 'Marsabit', code: '101' },
  { name: 'Matuu', code: '039' },
  { name: 'Maua', code: '040' },
  { name: 'Mayfair Supreme', code: '151' },
  { name: 'Mbale', code: '096' },
  { name: 'Mbita Point', code: '076' },
  { name: 'Meru', code: '014' },
  { name: 'Meru Makutano', code: '104' },
  { name: 'Migori', code: '116' },
  { name: 'Moi Avenue', code: '047' },
  { name: 'Molo', code: '023' },
  { name: 'Mombasa Digo Road', code: '046' },
  { name: 'Mombasa Moi Avenue', code: '025' },
  { name: 'Mombasa Road', code: '108' },
  { name: 'Mombasa Supreme Centre', code: '156' },
  { name: 'Moyale', code: '102' },
  { name: 'Mpeketoni', code: '127' },
  { name: 'Mtwapa', code: '119' },
  { name: 'Mukurwe-Ini', code: '083' },
  { name: 'Mumias', code: '068' },
  { name: 'Muranga', code: '022' },
  { name: 'Murarandia', code: '006' },
  { name: 'Mutomo', code: '167' },
  { name: 'Mwea', code: '038' },
  { name: 'Mwingi', code: '059' },
  { name: 'Nairobi West', code: '128' },
  { name: 'Naivasha', code: '020' },
  { name: 'Nakuru Gatehouse', code: '013' },
  { name: 'Nakuru Kenyatta Avenue', code: '031' },
  { name: 'Nakuru Westside Mall', code: '146' },
  { name: 'Namanga', code: '085' },
  { name: 'Nandi Hills', code: '092' },
  { name: 'Nanyuki', code: '027' },
  { name: 'Narok', code: '036' },
  { name: 'Ngara', code: '091' },
  { name: 'Ngong', code: '073' },
  { name: 'Nkubu', code: '037' },
  { name: 'Nyahururu', code: '016' },
  { name: 'Nyali', code: '138' },
  { name: 'Nyali Supreme', code: '154' },
  { name: 'Nyamira', code: '052' },
  { name: 'Nyeri', code: '011' },
  { name: 'Nyeri Kimathi Way', code: '115' },
  { name: 'Ol-Kalou', code: '062' },
  { name: 'Ongata Rongai', code: '061' },
  { name: 'OTC', code: '088' },
  { name: 'Othaya', code: '008' },
  { name: 'Oyugis', code: '150' },
  { name: 'Parliament Rd Corporate', code: '177' },
  { name: 'Ridgeways', code: '134' },
  { name: 'Ruai', code: '144' },
  { name: 'Ruaka', code: '174' },
  { name: 'Ruiru', code: '087' },
  { name: 'Rumuruti', code: '183' },
  { name: 'Runyenjes', code: '135' },
  { name: 'Siaya', code: '097' },
  { name: 'Syokimau Gateway mall', code: '176' },
  { name: 'Tala', code: '090' },
  { name: 'Taveta', code: '142' },
  { name: 'Tea Room', code: '094' },
  { name: 'Thika Kenyatta Highway', code: '034' },
  { name: 'Thika Makongeni', code: '171' },
  { name: 'Thika Plaza', code: '009' },
  { name: 'Thika Supreme', code: '155' },
  { name: 'Tom Mboya', code: '047' },
  { name: 'Ukunda', code: '044' },
  { name: 'UN Gigiri Supreme', code: '162' },
  { name: 'Utawala', code: '179' },
  { name: 'Voi', code: '079' },
  { name: 'Wajir', code: '103' },
  { name: 'Wangige Sub Branch', code: '178' },
  { name: 'Westlands', code: '055' },
  { name: 'Westlands Supreme', code: '140' },
  { name: 'Wote', code: '067' },
];
