export const cities = [
  'Abuja, Nigeria',
  'Accra, Ghana',
  'Addis Ababa, Ethiopia',
  'Algiers, Algeria',
  'Antananarivo, Madagascar',
  'Asmara, Eritrea',
  'Bamako, Mali',
  'Bangui, Central African Republic',
  'Banjul, The Gambia',
  'Bissau, Guinea-Bissau',
  'Brazzaville, Republic of the Congo',
  'Cairo, Egypt',
  'Conakry, Guinea',
  'Dakar, Senegal',
  'Djibouti, Djibouti',
  'Dodoma, Tanzania',
  'Freetown, Sierra Leone',
  'Gaborone, Botswana',
  'Harare, Zimbabwe',
  'Kampala, Uganda',
  'Khartoum, Sudan',
  'Kigali, Rwanda',
  'Kinshasa, Democratic Republic of the Congo',
  'Libreville, Gabon',
  'Lilongwe, Malawi',
  'Lome, Togo',
  'Luanda, Angola',
  'Lusaka, Zambia',
  'Maputo, Mozambique',
  'Maseru, Lesotho',
  'Mbabane, Eswatini',
  'Mogadishu, Somalia',
  'Monrovia, Liberia',
  'Moroni, Comoros',
  "N'Djamena, Chad",
  'Nairobi, Kenya',
  'Niamey, Niger',
  'Nouakchott, Mauritania',
  'Ouagadougou, Burkina Faso',
  'Port Louis, Mauritius',
  'Praia, Cape Verde',
  'Pretoria, South Africa',
  'Rabat, Morocco',
  'Sao Tome, Sao Tome and Principe',
  'Tripoli, Libya',
  'Tunis, Tunisia',
  'Victoria, Seychelles',
  'Windhoek, Namibia',
  'Yaounde, Cameroon',
  'London, United Kingdom',
  'Paris, France',
  'Berlin, Germany',
  'Madrid, Spain',
  'Rome, Italy',
  'Amsterdam, Netherlands',
  'Vienna, Austria',
  'Prague, Czech Republic',
  'Athens, Greece',
  'Warsaw, Poland',
  'São Paulo, Brazil',
  'Buenos Aires, Argentina',
  'Lima, Peru',
  'Bogotá, Colombia',
  'Rio de Janeiro, Brazil',
  'Santiago, Chile',
  'Caracas, Venezuela',
  'Quito, Ecuador',
  'Lima, Peru',
  'Asunción, Paraguay',
  'Montevideo, Uruguay',
  'La Paz, Bolivia',
  'Brasília, Brazil',
  'Manaus, Brazil',
  'Medellín, Colombia',
  'Guayaquil, Ecuador',
  'Recife, Brazil',
  'Fortaleza, Brazil',
  'Santa Cruz de la Sierra, Bolivia',
  'Valparaíso, Chile',
  'Tokyo, Japan',
  'Mumbai, India',
  'Shanghai, China',
  'Karachi, Pakistan',
  'Beijing, China',
  'Istanbul, Turkey',
  'Dhaka, Bangladesh',
  'Moscow, Russia',
  'Manila, Philippines',
  'Tianjin, China',
  'Mumbai, India',
  'Delhi, India',
  'Seoul, South Korea',
  'Jakarta, Indonesia',
  'Lahore, Pakistan',
  'Osaka, Japan',
  'Cairo, Egypt',
  'Chongqing, China',
  'Shenzhen, China',
  'Bangalore, India',
  'Kolkata, India',
  'Ho Chi Minh City, Vietnam',
  'Tehran, Iran',
  'Bangkok, Thailand',
  'Istanbul, Turkey',
  'Cairo, Egypt',
  'Riyadh, Saudi Arabia',
  'Baghdad, Iraq',
  'Tel Aviv, Israel',
  'Dubai, United Arab Emirates',
  'Amman, Jordan',
  'Doha, Qatar',
  'Kuwait City, Kuwait',
  'Muscat, Oman',
  'Beirut, Lebanon',
  'Manama, Bahrain',
  'Damascus, Syria',
  "Sana'a, Yemen",
  'Khartoum, Sudan',
  'Nicosia, Cyprus',
  'Ankara, Turkey',
  'Jerusalem, Israel',
  'Abu Dhabi, United Arab Emirates',
  'Aden, Yemen',
  'Erbil, Iraq',
  'Jeddah, Saudi Arabia',
  'Aleppo, Syria',
  'New York, New York',
  'Los Angeles, California',
  'Chicago, Illinois',
  'Houston, Texas',
  'Phoenix, Arizona',
  'Philadelphia, Pennsylvania',
  'San Antonio, Texas',
  'San Diego, California',
  'Dallas, Texas',
  'San Jose, California',
  'Austin, Texas',
  'Jacksonville, Florida',
  'San Francisco, California',
  'Columbus, Ohio',
  'Indianapolis, Indiana',
  'Fort Worth, Texas',
  'Charlotte, North Carolina',
  'Seattle, Washington',
  'Denver, Colorado',
  'Washington, D.C., District of Columbia',
  'Boston, Massachusetts',
  'El Paso, Texas',
  'Detroit, Michigan',
  'Nashville, Tennessee',
  'Memphis, Tennessee',
];
