export const clusters_c = [
  {
    'Human Health Science': [
      'Bachelor Of Dental Surgery',
      'Bachelor Of Medicine & Bachelor Of Surgery (M.B.Ch.B.)',
      'Bachelor Of Medicine And Bachelor Of Surgery (Mbchb)',
      'Bachelor Of Medicine And Bachelor Of Surgery (With It)',
      'Bachelor Of Nursing',
      'Bachelor Of Pharmacy',
      'Bachelor Of Physiotherapy',
      'Bachelor Of Population Health',
      'Bachelor Of Science (Health Promotion)',
      'Bachelor Of Science (Health Records & Information Mgt.)',
      'Bachelor Of Science (Horticultural Science & Management)',
    ],
  },
  {
    Law: [
      'Bachelor Of Laws (Ll.B.)',
      'Bachelor Of Laws (Llb)',
      'Bachelor Of Laws And Sharia (Ll.B.)',
    ],
  },

  {
    'Business Related': [
      'Accounting Technician Diploma',
      'Bachelor In Banking And Finance',
      'Bachelor In Business Administration',
      'Bachelor In Business Administration In Marketing',
      'Bachelor Of Applied Economics, With It',
      'Bachelor Of Financial Economics',
      'Bachelor Of Accountancy And Financial Management',
      'Bachelor Of Accounting And Finance',
      'Bachelor Of Actuarial Science',
      'Bachelor Of Agribusiness Management',
      'Bachelor Of Agricultural Economics And Agribusiness',
      'Bachelor Of Business And Information Technology',
      'Bachelor Of Business And Management',
      'Bachelor Of Business And Office Management',
      'Bachelor Of Business Entrepreneurship, With It',
      'Bachelor Of Business Information And Management',
      'Bachelor Of Business Information Technology',
      'Bachelor Of Business Leadership',
      'Bachelor Of Business Management',
      'Bachelor Of Business Management (Civil Aviation Management)',
      'Bachelor Of Business Management (Marine Business Management)',
      'Bachelor Of Business Management And Information Technology',
      'Bachelor Of Catering And Hotel Management',
      'Bachelor Of Commerce',
      'Bachelor Of Commerce (B.Com)',
      'Bachelor Of Commerce In Human Resources Management',
      'Bachelor Of Commerce In Management Information Systems',
      'Bachelor Of Commerce(B.Com)',
      'Bachelor Of Economics',
      'Bachelor Of Economics & Finance',
      'Bachelor Of Economics & Statistics',
      'Bachelor Of Economics And Finance',
      'Bachelor Of Economics And Finance, With It',
      'Bachelor Of Economics And Statistics',
      'Bachelor Of Economics And Statistics, With It',
      'Bachelor Of Eco-Tourism And Hospitality Management',
      'Bachelor Of Hotel & Hospitality Management',
      'Bachelor Of Hotel Management',
      'Bachelor Of Hotels And Hospitality Management',
      'Bachelor Of Human Resource Management',
      'Bachelor Of Human Resources Management',
      'Bachelor Of Management And Leadership',
      'Bachelor Of Management And Office Administration',
      'Bachelor Of Management Information Systems',
      'Bachelor Of Science (Accountancy)',
      'Bachelor Of Science (Accounting & Finance, With It)',
      'Bachelor Of Science (Actuarial Science With It)',
      'Bachelor Of Science (Actuarial Science)',
      'Bachelor Of Science (Actuarial Science, With It)',
      'Bachelor Of Science (Agri Business Management)',
      'Bachelor Of Science (Agribusiness Management & Trade)',
      'Bachelor Of Science (Agribusiness Management)',
      'Bachelor Of Science (Agribusiness Management, With It)',
      'Bachelor Of Science (Agribusiness)',
      'Bachelor Of Science (Agricultural & Bio-Systems Engineering)',
      'Bachelor Of Science (Agricultural And Biosystems Engineering)',
      'Bachelor Of Science (Agricultural Biotechnology)',
      'Bachelor Of Science (Agricultural Economics)',
      'Bachelor Of Science (Agricultural Economics & Resource Management)',
      'Bachelor Of Science (Agricultural Economics And Resource Management)',
      'Bachelor Of Science (Agricultural Economics And Rural Development)',
      'Bachelor Of Science (Agricultural Economics, With It)',
      'Bachelor Of Science (Agricultural Education & Extension)',
      'Bachelor Of Science (Agricultural Education And Extension)',
      'Bachelor Of Science (Agricultural Engineering)',
      'Bachelor Of Science (Agricultural Extension And Education)',
      'Bachelor Of Science (Agricultural Extension And Rural Development)',
      'Bachelor Of Science (Agricultural Extension Education)',
      'Bachelor Of Science (Agricultural Resource Management)',
      'Bachelor Of Science (Agriculture & Human Ecology Extension)',
      'Bachelor Of Science (Agriculture Education & Extension)',
      'Bachelor Of Science (Agriculture Education And Extension)',
      'Bachelor Of Science (Agriculture)',
      'Bachelor Of Science (Agroforestry & Rural Development)',
      'Bachelor Of Science (Agronomy, With It)',
      'Bachelor Of Science (Analytical Chemistry With Management)',
      'Bachelor Of Science (Analytical Chemistry)',
      'Bachelor Of Science (Analytical Chemistry, With It)',
      'Bachelor Of Science (Animal Health And Production)',
      'Bachelor Of Science (Animal Health, Production & Processing)',
      'Bachelor Of Science (Animal Production & Health Management)',
      'Bachelor Of Science (Animal Science & Management)',
      'Bachelor Of Science (Animal Science)',
      'Bachelor Of Science (Animal Science, With It)',
      'Bachelor Of Science (Apparel & Fashion Technology)',
      'Bachelor Of Science (Applied Aquatic Science)',
      'Bachelor Of Science (Applied Bioengineering)',
      'Bachelor Of Science (Applied Biology)',
      'Bachelor Of Science (Applied Computer Science)',
      'Bachelor Of Science (Applied Statistics With Computing)',
      'Bachelor Of Science (Applied Statistics With Programming)',
      'Bachelor Of Science (Applied Statistics)',
      'Bachelor Of Science (Applied Statistics, With It)',
      'Bachelor Of Science (Aquatic Resources Conservation And Development, With It)',
      'Bachelor Of Science (Astronomy And Astrophysics)',
      'Bachelor Of Science (B.Sc)',
      'Bachelor Of Science (Basic Science, With It)',
      'Bachelor Of Science (Biochemistry And Molecular Biology)',
      'Bachelor Of Science (Biochemistry)',
      'Bachelor Of Science (Biochemistry, With It)',
      'Bachelor Of Science (Biology)',
      'Bachelor Of Science (Biomedical Engineering)',
      'Bachelor Of Science (Biomedical Science & Technology)',
      'Bachelor Of Science (Biomedical Science And Technology',
      'Bachelor Of Science (Biomedical Science And Technology)',
      'Bachelor Of Science (Biostatistics)',
      'Bachelor Of Science (Biosystems Engineering)',
      'Bachelor Of Science (Biotechnology)',
      'Bachelor Of Science (Bsc.)',
      'Bachelor Of Science (Business Computing)',
      'Bachelor Of Science (Cellular And Molecular Biology)',
      'Bachelor Of Science (Chemistry)',
      'Bachelor Of Science (Civil And Structural Engineering)',
      'Bachelor Of Science (Civil Engineering)',
      'Bachelor Of Science (Climate Change And Development, With It)',
      'Bachelor Of Science (Clothing Textile & Interior Design)',
      'Bachelor Of Science (Coastal & Marine Resource Management',
      'Bachelor Of Science (Communication & Journalism)',
      'Bachelor Of Science (Communication And Journalism)',
      'Bachelor Of Science (Communication And Public Relations)',
      'Bachelor Of Science (Community Development And Environment)',
      'Bachelor Of Science (Community Development)',
      'Bachelor Of Science (Community Health & Development)',
      'Bachelor Of Science (Community Health And Development)',
      'Bachelor Of Science (Community Resource Management)',
      'Bachelor Of Science (Computer Science',
      'Bachelor Of Science (Computer Science)',
      'Bachelor Of Science (Computer Security And Forensics)',
      'Bachelor Of Science (Computer Technology)',
      'Bachelor Of Science (Conservation Biology)',
      'Bachelor Of Science (Control And Instrumentation)',
      'Bachelor Of Science (Corporate Communication And Management)',
      'Bachelor Of Science (Counselling Psychology)',
      'Bachelor Of Science (Criminology And Security Studies)',
      'Bachelor Of Science (Crop Improvement & Protection)',
      'Bachelor Of Science (Disaster Management And Peace Studies)',
      'Bachelor Of Science (Disaster Mitigation And Sustainable Development)',
      'Bachelor Of Science (Disaster Preparedness And Environment Technology)',
      'Bachelor Of Science (Disaster Risk Management And Sustainable Development)',
      'Bachelor Of Science (Dry Land, Agriculture & Enterprise Development)',
      'Bachelor Of Science (Dryland Agriculture)',
      'Bachelor Of Science (Dryland Animal Science)',
      'Bachelor Of Science (Earth Science, With It)',
      'Bachelor Of Science (Economics & Statistics)',
      'Bachelor Of Science (Economics And Statistics)',
      'Bachelor Of Science (Ecotourism & Hospitality Management)',
      'Bachelor Of Science (Eco-Tourism, Hotel And Institution Management, With It)',
      'Bachelor Of Science (Electrical & Electronics Engineering)',
      'Bachelor Of Science (Electrical And Communication Engineering)',
      'Bachelor Of Science (Electrical And Electronic Engineering)',
      'Bachelor Of Science (Electrical And Electronics Engineering)',
      'Bachelor Of Science (Electronic And Computer Engineering)',
      'Bachelor Of Science (Electronics)',
      'Bachelor Of Science (Emergency Management & Humanitarian Assistance)',
      'Bachelor Of Science (Energy Engineering)',
      'Bachelor Of Science (Entrepreneurship And Small Enterprises Management)',
      'Bachelor Of Science (Entrepreneurship Studies)',
      'Bachelor Of Science (Entrepreneurship)',
      'Bachelor Of Science (Environment Management And Conservation)',
      'Bachelor Of Science (Environmental Conservation And Natural Resources Management)',
      'Bachelor Of Science (Environmental Education)',
      'Bachelor Of Science (Environmental Health)',
      'Bachelor Of Science (Environmental Management)',
      'Bachelor Of Science (Environmental Science)',
      'Bachelor Of Science (Environmental Science, With It)',
      'Bachelor Of Science (Environmental Sciences)',
      'Bachelor Of Science (Event And Convention Management)',
      'Bachelor Of Science (Exercise & Sport Science)',
      'Bachelor Of Science (Fashion Design & Marketing)',
      'Bachelor Of Science (Fashion Design And Textile Technology)',
      'Bachelor Of Science (Finance)',
      'Bachelor Of Science (Financial Engineering)',
      'Bachelor Of Science (Fisheries & Aquatic Sciences)',
      'Bachelor Of Science (Fisheries And Aquaculture Management)',
      'Bachelor Of Science (Fisheries And Natural Resources, With It)',
      'Bachelor Of Science (Food Nutrition & Dietetics)',
      'Bachelor Of Science (Food Nutrition And Dietetics)',
      'Bachelor Of Science (Food Operations Management)',
      'Bachelor Of Science (Food Science & Nutrition)',
      'Bachelor Of Science (Food Science & Technology',
    ],
  },
  {
    Education: [
      'Bachelor Of Education (Arts - Business Studies)',
      'Bachelor Of Education (Arts - Geo, Mat & Bus)',
      'Bachelor Of Education (Arts)',
      'Bachelor Of Education (Arts) French',
      'Bachelor Of Education (Arts) German',
      'Bachelor Of Education (Arts) Music',
      'Bachelor Of Education (Arts) With Guidance And Counselling',
      'Bachelor Of Education (Arts) With Special Needs Education',
      'Bachelor Of Education (Arts, With It)',
      'Bachelor Of Education (Early Childhood And Primary Education)',
      'Bachelor Of Education (Early Childhood Development Education)',
      'Bachelor Of Education (Early Childhood Development)',
      'Bachelor Of Education (Early Childhood Education)',
      'Bachelor Of Education (Early Childhood Education, With It)',
      'Bachelor Of Education (Early Childhood)',
      'Bachelor Of Education (French)',
      'Bachelor Of Education (Guidance And Counselling)',
      'Bachelor Of Education (Home Science , With It)',
      'Bachelor Of Education (Home Science And Technology)',
      'Bachelor Of Education (Ict)',
      'Bachelor Of Education (Library Science)',
      'Bachelor Of Education (Physical Education And Sports)',
      'Bachelor Of Education (Physical Education)',
      'Bachelor Of Education (Science)',
      'Bachelor Of Education (Science) Physics, Chemistry, Biology, Mathematics, And Computer Studies',
      'Bachelor Of Education (Science) With Guidance And Counseling',
      'Bachelor Of Education (Science) With Special Needs Education',
      'Bachelor Of Education (Science, With It)',
      'Bachelor Of Education (Special Needs Education - Secondary Option)',
      'Bachelor Of Education (Special Needs Education)',
      'Bachelor Of Education (Special Needs Education, With It)',
      'Bachelor Of Education (Technology Education)',
      'Bachelor Of Education Arts',
      'Bachelor Of Education Arts (History, Cre, Geography, English, Kiswahili, Mathematics, Business Studies)',
      'Bachelor Of Education Arts (Home Economics)',
      'Bachelor Of Education In Early Childhood Education',
      'Bachelor Of Education In Early Childhood Studies',
      'Bachelor Of Education In Special Education',
      'Bachelor Of Education In Special Needs Education',
      'Bachelor Of Education In Technology (Building & Civil Technology)',
      'Bachelor Of Education In Technology (Civil Engineering)',
      'Bachelor Of Education In Technology (Electrical & Electronic Engineering)',
      'Bachelor Of Education In Technology (Mechanical Engineering)',
      'Bachelor Of Education In Technology (Mechanicaltechnology)',
      'Bachelor Of Education Science (Agriculture)',
      'Bachelor Of Education Special Needs Education Secondary Option',
      'Bachelor Of Education Technology (Civil Engineering)',
      'Bachelor Of Education With Guidance And Counselling',
      'Bachelor Of Education(Arts) With It',
      'Bachelor Of Education(Early Childhood Development)',
      'Bachelor Of Education(Major Accounting And Business Administration)',
      'Bachelor Of Education(Science With It)',
    ],
  },
  {
    'Actuaries & Data Science': [
      'Bachelor Of Actuarial Science',
      'Bachelor Of Science (Actuarial Science With It)',
      'Bachelor Of Science (Actuarial Science)',
      'Bachelor Of Science (Actuarial Science, With It)',
    ],
  },
  {
    'Agriculture & Food Security': [
      'Bachelor Of Agribusiness Management',
      'Bachelor Of Agricultural Education And Extension',
      'Bachelor Of Agricultural Economics And Agribusiness',
      'Bachelor Of Agricultural Economics, With It',
      'Bachelor Of Agricultural Resource Management',
      'Bachelor Of Agriculture Economics & Resource Management',
      'Bachelor Of Agriculture Education & Extension',
      'Bachelor Of Agriculture Education And Extension',
      'Bachelor Of Agriculture',
    ],
  },
  {
    'Information Communication Technology': [
      'Bachelor Of Information Communication Technology',
      'Bachelor Of Information Science',
      'Bachelor Of Information Technology',
      'Bachelor Of Science (Computer Science)',
      'Bachelor Of Science (Computer Science)',
      'Bachelor Of Science (Computer Security And Forensics)',
      'Bachelor Of Science (Computer Technology)',
    ],
  },
  {
    'Built Environment (Architecture, Quantity Surveying, Real Estate e.t.c)': [
      'Bachelor Of Architectural Studies/Bachelor Of Architecture',
      'Bachelor Of Architecture',
      'Bachelor Of Arts (Interior Design, With It)',
      'Bachelor Of Arts (Urban And Regional Planning, With It)',
      'Bachelor Of Engineering (Aeronautical Engineering)',
      'Bachelor Of Engineering (Agricultural & Bio-Systems Engineering)',
      'Bachelor Of Engineering (Chemical And Process Engineering)',
      'Bachelor Of Engineering (Chemical Engineering)',
      'Bachelor Of Engineering (Civil & Structural Engineering)',
      'Bachelor Of Engineering (Civil And Structural Engineering)',
      'Bachelor Of Engineering (Civil Engineering)',
      'Bachelor Of Engineering (Electrical And Electronic Engineering)',
      'Bachelor Of Engineering (Electrical And Electronics Engineering)',
      'Bachelor Of Engineering (Electrical And Telecommunication Engineering)',
      'Bachelor Of Engineering (Geospatial Engineering)',
      'Bachelor Of Engineering (Industrial And Textile Engineering)',
      'Bachelor Of Engineering (Mechanical & Production Engineering)',
      'Bachelor Of Engineering (Mechanical And Production Engineering)',
      'Bachelor Of Engineering (Mechanical Engineering)',
      'Bachelor Of Real Estate',
      'Bachelor Of Science (Civil And Structural Engineering)',
      'Bachelor Of Science (Civil Engineering)',
      'Bachelor Of Science (Environmental Management)',
      'Bachelor Of Science (Geospatial Engineering)',
      'Bachelor Of Science (Quantity Surveying)',
    ],
  },
  {
    'Social Science (anthropology, psychology, sociology e.t.c)': [
      'Bachelor Of Arts (Anthropology)',
      'Bachelor Of Arts (Business Studies, With It)',
      'Bachelor Of Arts (Communication & Media Technology, With It)',
      'Bachelor Of Arts (Communication And Media)',
      'Bachelor Of Arts (Community Development)',
      'Bachelor Of Arts (Counseling)',
      'Bachelor Of Arts (Counselling Psychology)',
      'Bachelor Of Arts (Criminology & Security Studies)',
      'Bachelor Of Arts (Criminology And Penology)',
      'Bachelor Of Arts (Criminology And Security Studies)',
      'Bachelor Of Arts (Criminology, With It)',
      'Bachelor Of Arts (Design)',
      'Bachelor Of Arts (Development Studies, With It)',
      'Bachelor Of Arts (Disaster Management, With It)',
      'Bachelor Of Arts (Drama And Theatre Studies, With It)',
      'Bachelor Of Arts (Economics & Sociology)',
      'Bachelor Of Arts (Economics And Sociology)',
      'Bachelor Of Arts (Economics)',
      'Bachelor Of Arts (Economics, With It)',
      'Bachelor Of Arts (English & Communication)',
      'Bachelor Of Arts (Fine Art, With It)',
      'Bachelor Of Arts (Fine Arts)',
      'Bachelor Of Arts (French)',
      'Bachelor Of Arts (French, With It)',
      'Bachelor Of Arts (Gender And Development Studies)',
      'Bachelor Of Arts (Gender And Development)',
      'Bachelor Of Arts (Gender, Women And Development Studies)',
      'Bachelor Of Arts (Geography)',
      'Bachelor Of Arts (German)',
      'Bachelor Of Arts (History & Economics)',
      'Bachelor Of Arts (History And Archaeology)',
      'Bachelor Of Arts (History And Archaeology, With It)',
      'Bachelor Of Arts (History And Economics)',
      'Bachelor Of Arts (History)',
      'Bachelor Of Arts (Human Rights)',
      'Bachelor Of Arts (Interior Design, With It)',
      'Bachelor Of Arts (International Relations And Diplomacy ,With It)',
      'Bachelor Of Arts (International Relations And Diplomacy)',
      'Bachelor Of Arts (Kiswahili)',
      'Bachelor Of Arts (Kiswahili, With It)',
      'Bachelor Of Arts (Linguistic)',
      'Bachelor Of Arts (Linguistics And Literature)',
      'Bachelor Of Arts (Linguistics, Media And Communication)',
      'Bachelor Of Arts (Literature)',
      'Bachelor Of Arts (Literature, With It)',
      'Bachelor Of Arts (Music)',
      'Bachelor Of Arts (Peace And Conflict Studies)',
      'Bachelor Of Arts (Penology, Correction And Administration)',
      'Bachelor Of Arts (Philosophy)',
      'Bachelor Of Arts (Philosophy, With It)',
      'Bachelor Of Arts (Planning)',
      'Bachelor Of Arts (Political Science & Public Administration)',
      'Bachelor Of Arts (Political Science And Public Administration)',
      'Bachelor Of Arts (Psychology)',
      'Bachelor Of Arts (Public Administration And Political Science)',
      'Bachelor Of Arts (Public Administration)',
      'Bachelor Of Arts (Religious Studies)',
      'Bachelor Of Arts (Social Work And Sociology)',
      'Bachelor Of Arts (Social Work)',
      'Bachelor Of Arts (Sociology & Religion)',
      'Bachelor Of Arts (Sociology And Anthropology, With It)',
      'Bachelor Of Arts (Sociology And Technology)',
      'Bachelor Of Arts (Sociology)',
      'Bachelor Of Arts (Textiles, Fashion Design And Merchandising, With It)',
      'Bachelor Of Arts (Theater Arts & Film Technology)',
      'Bachelor Of Arts (Urban And Regional Planning, With It)',
      'Bachelor Of Arts (With Education)',
      'Bachelor Of Arts (With It)',
      'Bachelor Of Arts Community Development',
      'Bachelor Of Arts In Anthropology',
      'Bachelor Of Arts In Communication',
      'Bachelor Of Arts In Community Development',
      'Bachelor Of Arts In Conflicts And Security Studies',
      'Bachelor Of Arts In Counseling Psychology',
      'Bachelor Of Arts In Criminal Justice And Security Management',
      'Bachelor Of Arts In Criminology, Criminal Justice And Public Safety',
      'Bachelor Of Arts In Development Studies',
      'Bachelor Of Arts In Economics',
      'Bachelor Of Arts In Economics And Business Studies',
      'Bachelor Of Arts In English And Linguistics',
      'Bachelor Of Arts In Geography',
      'Bachelor Of Arts In Guidance And Counselling',
      'Bachelor Of Arts In History',
      'Bachelor Of Arts In History & International Studies',
      'Bachelor Of Arts In History And Economics',
      'Bachelor Of Arts In International Relations',
      'Bachelor Of Arts In International Relations And Diplomacy',
      'Bachelor Of Arts In Journalism',
      'Bachelor Of Arts In Journalism And Digital Media',
      'Bachelor Of Arts In Journalism And Mass Communication',
      'Bachelor Of Arts In Justice And Security Studies',
      'Bachelor Of Arts In Kiswahili',
      'Bachelor Of Arts In Kiswahili And Geography',
      'Bachelor Of Arts In Kiswahili And Media Studies',
      'Bachelor Of Arts In Language And Communication',
      'Bachelor Of Arts In Leadership And Management',
      'Bachelor Of Arts In Literature, Theatre And Film',
      'Bachelor Of Arts In Mass Communication',
      'Bachelor Of Arts In Mass Media And Communication',
      'Bachelor Of Arts In Mathematics And Economics',
      'Bachelor Of Arts In Pastoral Theology',
      'Bachelor Of Arts In Peace Studies And Conflict Resolution',
      'Bachelor Of Arts In Philosophy',
      'Bachelor Of Arts In Philosophy And Leadership Studies',
      'Bachelor Of Arts In Political Science',
      'Bachelor Of Arts In Political Science And Public Administration',
      'Bachelor Of Arts In Psychology',
      'Bachelor Of Arts In Public Administration',
      'Bachelor Of Arts In Public Administration And Governance',
      'Bachelor Of Arts In Religion',
      'Bachelor Of Arts In Religious Studies',
      'Bachelor Of Arts In Security Studies And Criminology',
      'Bachelor Of Arts In Social Communication',
      'Bachelor Of Arts In Sociology',
      'Bachelor Of Arts In Theology',
      'Bachelor Of Arts In Translation Studies',
      'Bachelor Of Arts Performing Arts And Film Technology',
      'Bachelor Of Arts(Spatial Planning)',
      'Bachelor Of Broadcast Journalism',
      'Bachelor Of Broadcast Production',
      'Bachelor Of Business Administration',
      'Bachelor Of Business Administration ( With It)',
      'Bachelor Of Business Administration And Management',
      'Bachelor Of Business Administration In Accounting',
      'Bachelor Of Business Administration In Finance',
      'Bachelor Of Business Administration In Management',
      'Bachelor Of Business Administration With It',
      'Bachelor Of Business And Information Technology',
      'Bachelor Of Business And Management',
      'Bachelor Of Business And Office Management',
      'Bachelor Of Business Entrepreneurship , With It',
      'Bachelor Of Business Information And Management',
      'Bachelor Of Business Information Technology',
      'Bachelor Of Business Leadership',
      'Bachelor Of Business Management',
      'Bachelor Of Business Management (Civil Aviation Management)',
      'Bachelor Of Business Management (Marine Business Management)',
      'Bachelor Of Business Management And Information Technology',
      'Bachelor Of Catering And Hotel Management',
      'Bachelor Of Commerce',
      'Bachelor Of Commerce (B.Com)',
      'Bachelor Of Commerce In Human Resources Management',
      'Bachelor Of Commerce In Management Information Systems',
      'Bachelor Of Commerce(B.Com)',
      'Bachelor Of Communication & Journalism',
      'Bachelor Of Communication & Public Relations',
      'Bachelor Of Communication And Media Studies',
      'Bachelor Of Communication In Multimedia Journalism',
      'Bachelor Of Community Development',
      'Bachelor Of Conflict Resolution And Humanitairan Assistance',
      'Bachelor Of Construction Management',
      'Bachelor Of Co-Operative Management',
      'Bachelor Of Co-Operatives And Community Development',
      'Bachelor Of Counseling Psychology',
      'Bachelor Of Criminology',
      'Bachelor Of Dental Surgery',
      'Bachelor Of Development Studies',
      'Bachelor Of Development Studies With It',
      'Bachelor Of Disaster Management & International Diplomacy',
      'Bachelor Of Economics',
      'Bachelor Of Economics & Finance',
      'Bachelor Of Economics & Statistics',
      'Bachelor Of Economics And Finance',
      'Bachelor Of Economics And Finance, With It',
      'Bachelor Of Economics And Statistics',
      'Bachelor Of Economics And Statistics, With It',
      'Bachelor Of Eco-Tourism And Hospitality Management',
      'Bachelor Of Education (Arts - Business Studies)',
      'Bachelor Of Education (Arts - Geo, Mat & Bus)',
      'Bachelor Of Education (Arts)',
      'Bachelor Of Education (Arts) French',
      'Bachelor Of Education (Arts) German',
      'Bachelor Of Education (Arts) Music',
      'Bachelor Of Education (Arts) With Guidance And Counselling',
      'Bachelor Of Education (Arts) With Special Needs Education',
      'Bachelor Of Education (Arts, With It)',
      'Bachelor Of Education (Early Childhood And Primary Education)',
      'Bachelor Of Education (Early Childhood Development Education)',
      'Bachelor Of Education (Early Childhood Development)',
      'Bachelor Of Education (Early Childhood Education)',
      'Bachelor Of Education (Early Childhood Education, With It)',
      'Bachelor Of Education (Early Childhood)',
      'Bachelor Of Education (French)',
      'Bachelor Of Education (Guidance And Counselling)',
      'Bachelor Of Education (Home Science , With It)',
      'Bachelor Of Education (Home Science And Technology)',
      'Bachelor Of Education (Ict)',
      'Bachelor Of Education (Library Science)',
      'Bachelor Of Education (Physical Education And Sports)',
      'Bachelor Of Education (Physical Education)',
      'Bachelor Of Education (Science)',
      'Bachelor Of Education (Science) Physics, Chemistry, Biology, Mathematics, And Computer Studies',
      'Bachelor Of Education (Science) With Guidance And Counseling ',
      'Bachelor Of Education (Science) With Special Needs Education',
      'Bachelor Of Education (Science, With It)',
      'Bachelor Of Education (Special Needs Education - Secondary Option)',
      'Bachelor Of Education (Special Needs Education)',
      'Bachelor Of Education (Special Needs Education, With It)',
      'Bachelor Of Education (Technology Education)',
      'Bachelor Of Education Arts',
      'Bachelor Of Education Arts (History, Cre, Geography, English, Kiswahili, Mathematics, Business Studies)',
      'Bachelor Of Education Arts (Home Economics)',
      'Bachelor Of Education In Early Childhood Education',
      'Bachelor Of Education In Early Childhood Studies',
      'Bachelor Of Education In Special Education',
      'Bachelor Of Education In Special Needs Education',
      'Bachelor Of Education In Technology (Building & Civil Technology)',
      'Bachelor Of Education In Technology (Civil Engineering)',
      'Bachelor Of Education In Technology (Electrical & Electronic Engineering)',
      'Bachelor Of Education In Technology (Mechanical Engineering)',
      'Bachelor Of Education In Technology (Mechanicaltechnology)',
      'Bachelor Of Education Science (Agriculture)',
      'Bachelor Of Education Special Needs Education Secondary Option',
      'Bachelor Of Education Technology (Civil Engineering)',
      'Bachelor Of Education With Guidance And Counselling',
      'Bachelor Of Education(Arts) With It',
      'Bachelor Of Education(Early Childhood Development)',
      'Bachelor Of Education(Major Accounting And Business Administration)',
      'Bachelor Of Education(Science With It)',
      'Bachelor Of Engineering (Aeronautical Engineering)',
      'Bachelor Of Engineering (Agricultural & Bio-Systems Engineering)',
      'Bachelor Of Engineering (Chemical And Process Engineering)',
      'Bachelor Of Engineering (Chemical Engineering)',
      'Bachelor Of Engineering (Civil & Structural Engineering)',
      'Bachelor Of Engineering (Civil And Structural Engineering)',
      'Bachelor Of Engineering (Civil Engineering)',
      'Bachelor Of Engineering (Electrical And Electronic Engineering)',
      'Bachelor Of Engineering (Electrical And Electronics Engineering)',
      'Bachelor Of Engineering (Electrical And Telecommunication Engineering)',
      'Bachelor Of Engineering (Geospatial Engineering)',
      'Bachelor Of Engineering (Industrial And Textile Engineering)',
      'Bachelor Of Engineering (Mechanical & Production Engineering)',
      'Bachelor Of Engineering (Mechanical And Production Engineering)',
      'Bachelor Of Engineering (Mechanical Engineering)',
      'Bachelor Of Entrepreneurship',
      'Bachelor Of Entrepreneurship And Enterprise Management',
      'Bachelor Of Entreprenuership & Small Business Management',
      'Bachelor Of Entreprenuership And Enterprise Management',
      'Bachelor Of Entreprenuership And Management',
      'Bachelor Of Environmental Planning & Management',
      'Bachelor Of Environmental Science',
      'Bachelor Of Environmental Science (Resource Conservation)',
      'Bachelor Of Environmental Studies',
      'Bachelor Of Environmental Studies (Arts)',
      'Bachelor Of Environmental Studies (Biology And Health)',
      'Bachelor Of Environmental Studies (Community Development)',
      'Bachelor Of Environmental Studies (Earth Sciences)',
      'Bachelor Of Environmental Studies (Environmental Resource Conservation)',
      'Bachelor Of Environmental Studies (Science)',
      'Bachelor Of Environmental Studies And Community Development',
      'Bachelor Of Film And Animation',
      'Bachelor Of Film And Animation Studies',
      'Bachelor Of Health Services Management',
      'Bachelor Of Hospitality And Institutional Management',
      'Bachelor Of Hospitality And Tourism Management',
      'Bachelor Of Hotel & Hospitality Management',
      'Bachelor Of Hotel And Hospitality Management',
      'Bachelor Of Human Resource Management',
      'Bachelor Of Information Communication Technology',
      'Bachelor Of Information Science',
      'Bachelor Of Information Technology',
      'Bachelor Of Information Technology (Hardware And Networking)',
      'Bachelor Of Information Technology (Software Development)',
      'Bachelor Of Information Technology And Business Information Systems',
      'Bachelor Of Information Technology And Management',
      'Bachelor Of Information Technology In Computer Networks And Security',
      'Bachelor Of Information Technology In Database Management',
      'Bachelor Of Information Technology In Information Security',
      'Bachelor Of Information Technology In Mobile Application Development',
      'Bachelor Of Information Technology In Software Development',
      'Bachelor Of Information Technology In Web Design And Development',
      'Bachelor Of Information Technology Management',
      'Bachelor Of Journalism',
      'Bachelor Of Journalism & Communication',
      'Bachelor Of Journalism & Mass Communication',
      'Bachelor Of Journalism And Digital Media',
      'Bachelor Of Journalism And Mass Communication',
      'Bachelor Of Journalism And Public Relations',
      'Bachelor Of Journalism And Public Relations & Advertising',
      'Bachelor Of Journalism And Public Relations (With It)',
      'Bachelor Of Journalism And Public Relations',
      'Bachelor Of Journalism With It',
      'Bachelor Of Kiswahili',
      'Bachelor Of Kiswahili And Communication',
      'Bachelor Of Kiswahili And Communication, With It',
      'Bachelor Of Kiswahili And Journalism',
      'Bachelor Of Kiswahili And Media Studies',
      'Bachelor Of Kiswahili With It',
      'Bachelor Of Landscape Architecture',
      'Bachelor Of Laws (Ll.B.)',
      'Bachelor Of Laws (Llb)',
      'Bachelor Of Laws And Sharia (Ll.B.)',
      'Bachelor Of Library & Information Science',
      'Bachelor Of Library And Information Science',
      'Bachelor Of Library And Information Studies',
      'Bachelor Of Management & Office Administration',
      'Bachelor Of Management And Office Administration',
      'Bachelor Of Management And Office Administration (Bmoa)',
      'Bachelor Of Management And Public Administration',
      'Bachelor Of Management Science',
      'Bachelor Of Management Science (Bms)',
      'Bachelor Of Management Science In Accounting',
      'Bachelor Of Management Science In Finance',
      'Bachelor Of Management Science In Human Resource Management',
      'Bachelor Of Management Science In Marketing',
      'Bachelor Of Management Science In Operations And Project Management',
      'Bachelor Of Management Science In Purchasing And Supplies Management',
      'Bachelor Of Management Science In Strategic Management',
      'Bachelor Of Management Science In Transport And Logistics Management',
      'Bachelor Of Management Science In Transport Management',
      'Bachelor Of Management Science(Public Sector Management)',
      'Bachelor Of Mass Communication',
      'Bachelor Of Mass Media And Communication',
      'Bachelor Of Mechanical Engineering',
      'Bachelor Of Medical Laboratory Sciences',
      'Bachelor Of Medical Laboratory Technology',
      'Bachelor Of Medicine & Bachelor Of Surgery',
      'Bachelor Of Medicine And Bachelor Of Surgery',
      'Bachelor Of Medicine And Bachelor Of Surgery (Mbchb)',
      'Bachelor Of Medicine And Bachelor Of Surgery (M.B.Ch.B.)',
      'Bachelor Of Medical Laboratory Science',
      'Bachelor Of Nursing',
      'Bachelor Of Nutrition And Dietetics',
      'Bachelor Of Operations And Project Management',
      'Bachelor Of Pharmacy',
      'Bachelor Of Procurement',
      'Bachelor Of Procurement & Contract Management',
      'Bachelor Of Procurement & Logistics Management',
      'Bachelor Of Procurement & Supply Chain Management',
      'Bachelor Of Procurement And Contract Management',
      'Bachelor Of Procurement And Logistics Management',
      'Bachelor Of Procurement And Supplies Management',
      'Bachelor Of Procurement And Supply Chain Management',
      'Bachelor Of Project Management',
      'Bachelor Of Public Administration',
      'Bachelor Of Public Health',
      'Bachelor Of Purchasing & Supplies Management',
      'Bachelor Of Quantity Surveying',
      'Bachelor Of Real Estate',
      'Bachelor Of Real Estate And Property Management',
      'Bachelor Of Real Estate Management',
      'Bachelor Of Records Management And Information Technology',
      'Bachelor Of Records Management And Information Technology, With It',
      'Bachelor Of Records Management And Information Technology',
      'Bachelor Of Records Management And Library Science',
      'Bachelor Of Science (Actuarial Science With It)',
      'Bachelor Of Science (Actuarial Science)',
      'Bachelor Of Science (Actuarial Science, With It)',
      'Bachelor Of Science (Aeronautical Engineering)',
      'Bachelor Of Science (Agribusiness Management)',
      'Bachelor Of Science (Agricultural Economics)',
      'Bachelor Of Science (Agricultural Education)',
      'Bachelor Of Science (Agricultural Education)',
      'Bachelor Of Science (Agricultural Economics)',
      'Bachelor Of Science (Agricultural Education And Extension)',
      'Bachelor Of Science (Agricultural Education)',
      'Bachelor Of Science (Agricultural Economics)',
      'Bachelor Of Science (Agricultural Economics, With It)',
      'Bachelor Of Science (Agricultural Economics)',
      'Bachelor Of Science (Agricultural Economics, With It)',
      'Bachelor Of Science (Agricultural Resource Management)',
      'Bachelor Of Science (Agriculture Economics & Resource Management)',
      'Bachelor Of Science (Agriculture Education & Extension)',
      'Bachelor Of Science (Agriculture Education And Extension)',
      'Bachelor Of Science (Agriculture Economics)',
      'Bachelor Of Science (Agriculture)',
      'Bachelor Of Science (Agroforestry)',
      'Bachelor Of Science (Analytical Chemistry)',
      'Bachelor Of Science (Applied Aquatic Science)',
      'Bachelor Of Science (Applied Biology)',
      'Bachelor Of Science (Applied Chemistry)',
      'Bachelor Of Science (Applied Computer Science)',
      'Bachelor Of Science (Applied Computer Science, With It)',
      'Bachelor Of Science (Applied Mathematics)',
      'Bachelor Of Science (Applied Microbiology)',
      'Bachelor Of Science (Applied Physics)',
      'Bachelor Of Science (Applied Statistics)',
      'Bachelor Of Science (Applied Zoology)',
      'Bachelor Of Science (Architecture)',
      'Bachelor Of Science (Biochemistry)',
      'Bachelor Of Science (Biochemistry, With It)',
      'Bachelor Of Science (Bioinformatics)',
      'Bachelor Of Science (Biological Science)',
      'Bachelor Of Science (Biology)',
      'Bachelor Of Science (Biomedical Science)',
      'Bachelor Of Science (Biotechnology)',
      'Bachelor Of Science (Botany)',
      'Bachelor Of Science (Building & Civil Engineering)',
      'Bachelor Of Science (Building Economics)',
      'Bachelor Of Science (Building Economics)',
      'Bachelor Of Science (Business & Information Technology)',
      'Bachelor Of Science (Business Administration)',
      'Bachelor Of Science (Business And Information Technology)',
      'Bachelor Of Science (Business Information Technology)',
      'Bachelor Of Science (Chemical And Process Engineering)',
      'Bachelor Of Science (Chemical Engineering)',
      'Bachelor Of Science (Chemistry)',
      'Bachelor Of Science (Civil & Structural Engineering)',
      'Bachelor Of Science (Civil And Structural Engineering)',
      'Bachelor Of Science (Civil Engineering)',
      'Bachelor Of Science (Clinical Medicine)',
      'Bachelor Of Science (Communication & Media Technology)',
      'Bachelor Of Science (Community Development)',
      'Bachelor Of Science (Computer Science)',
      'Bachelor Of Science (Computer Science, With It)',
      'Bachelor Of Science (Computer Security And Forensics)',
      'Bachelor Of Science (Computer Technology)',
      'Bachelor Of Science (Conservation Biology)',
      'Bachelor Of Science (Counselling Psychology)',
      'Bachelor Of Science (Criminology & Penology)',
      'Bachelor Of Science (Criminology & Security Studies)',
      'Bachelor Of Science (Criminology And Penology)',
      'Bachelor Of Science (Criminology And Security Studies)',
      'Bachelor Of Science (Criminology, Criminal Justice And Public Safety)',
      'Bachelor Of Science (Criminology)',
      'Bachelor Of Science (Crop Science)',
      'Bachelor Of Science (Data Science)',
      'Bachelor Of Science (Data Science, With It)',
      'Bachelor Of Science (Design)',
      'Bachelor Of Science (Diagnostic Radiography And Imaging)',
      'Bachelor Of Science (Disaster Management)',
      'Bachelor Of Science (Disaster Management, With It)',
      'Bachelor Of Science (Economics & Finance)',
      'Bachelor Of Science (Economics & Mathematics)',
      'Bachelor Of Science (Economics And Finance)',
      'Bachelor Of Science (Economics And Finance, With It)',
      'Bachelor Of Science (Economics)',
      'Bachelor Of Science (Economics, With It)',
      'Bachelor Of Science (Electrical & Electronics Engineering)',
      'Bachelor Of Science (Electrical And Electronics Engineering)',
      'Bachelor Of Science (Electronic & Computer Engineering)',
      'Bachelor Of Science (Electronic And Computer Engineering)',
      'Bachelor Of Science (Energy And Environmental Technology)',
      'Bachelor Of Science (Environmental Health)',
      'Bachelor Of Science (Environmental Management)',
      'Bachelor Of Science (Environmental Planning)',
      'Bachelor Of Science (Environmental Resource Conservation)',
      'Bachelor Of Science (Environmental Science)',
      'Bachelor Of Science (Environmental Studies)',
      'Bachelor Of Science (Environmental Studies, With It)',
      'Bachelor Of Science (Environmental Sustainability)',
      'Bachelor Of Science (Environmental, Water And Natural Resources Management)',
      'Bachelor Of Science (Epidemiology And Biostatistics)',
      'Bachelor Of Science (Fashion Design)',
      'Bachelor Of Science (Fashion Design, With It)',
      'Bachelor Of Science (Fashion Design)',
      'Bachelor Of Science (Fashion Merchandising)',
      'Bachelor Of Science (Fashion Merchandising, With It)',
      'Bachelor Of Science (Fashion Merchandising)',
      'Bachelor Of Science (Film Production And Animation)',
      'Bachelor Of Science (Financial Economics)',
      'Bachelor Of Science (Food Nutrition & Dietetics)',
      'Bachelor Of Science (Food Science & Management)',
      'Bachelor Of Science (Food Science & Nutrition)',
      'Bachelor Of Science (Food Science And Management)',
      'Bachelor Of Science (Food Science And Nutrition)',
      'Bachelor Of Science (Food Science)',
      'Bachelor Of Science (Food Science, With It)',
      'Bachelor Of Science (Food Security & Community Nutrition)',
      'Bachelor Of Science (Forensic Science)',
      'Bachelor Of Science (Forensic Science, With It)',
      'Bachelor Of Science (Forestry)',
      'Bachelor Of Science (Forestry, With It)',
      'Bachelor Of Science (Geographical Information Systems And Remote Sensing)',
      'Bachelor Of Science (Geographical Information Systems)',
      'Bachelor Of Science (Geographical Information Systems, With It)',
      'Bachelor Of Science (Geographical Information Systems)',
      'Bachelor Of Science (Geography)',
      'Bachelor Of Science (Geospatial Engineering)',
      'Bachelor Of Science (Geospatial Engineering)',
      'Bachelor Of Science (Horticulture)',
      'Bachelor Of Science (Hospitality Management)',
      'Bachelor Of Science (Hotel And Restaurant Management)',
      'Bachelor Of Science (Hotel Management)',
      'Bachelor Of Science (Human Nutrition & Dietetics)',
      'Bachelor Of Science (Human Resource Management)',
      'Bachelor Of Science (Hydrology And Water Resources Management)',
      'Bachelor Of Science (Industrial Chemistry)',
      'Bachelor Of Science (Industrial Mathematics)',
      'Bachelor Of Science (Industrial Mathematics, With It)',
      'Bachelor Of Science (Industrial Microbiology)',
      'Bachelor Of Science (Industrial Microbiology, With It)',
      'Bachelor Of Science (Industrial Physics)',
      'Bachelor Of Science (Information Sciences)',
      'Bachelor Of Science (Information Security And Forensics)',
      'Bachelor Of Science (Information Technology)',
      'Bachelor Of Science (Information Technology)',
      'Bachelor Of Science (Interior Design)',
      'Bachelor Of Science (Interior Design, With It)',
      'Bachelor Of Science (Interior Design)',
      'Bachelor Of Science (Kinesiology)',
      'Bachelor Of Science (Landscape Architecture)',
      'Bachelor Of Science (Leather Technology)',
      'Bachelor Of Science (Library And Information Science)',
      'Bachelor Of Science (Marine Biology)',
      'Bachelor Of Science (Marine Biology, With It)',
      'Bachelor Of Science (Marine Science And Fisheries)',
      'Bachelor Of Science (Mathematical Sciences)',
      'Bachelor Of Science (Mathematics & Computer Science)',
      'Bachelor Of Science (Mathematics And Computer Science)',
      'Bachelor Of Science (Mathematics And Economics)',
      'Bachelor Of Science (Mathematics)',
      'Bachelor Of Science (Mathematics, With It)',
      'Bachelor Of Science (Mechanical & Manufacturing Engineering)',
      'Bachelor Of Science (Mechanical & Production Engineering)',
      'Bachelor Of Science (Mechanical Engineering)',
      'Bachelor Of Science (Medical Laboratory Technology)',
      'Bachelor Of Science (Medical Laboratory Technology, With It)',
      'Bachelor Of Science (Medical Laboratory Technology)',
      'Bachelor Of Science (Medical Microbiology)',
      'Bachelor Of Science (Medical Microbiology, With It)',
      'Bachelor Of Science (Medical Physics)',
      'Bachelor Of Science (Meteorology)',
      'Bachelor Of Science (Microbiology & Biotechnology)',
      'Bachelor Of Science (Microbiology)',
      'Bachelor Of Science (Microbiology, With It)',
      'Bachelor Of Science (Mining & Mineral Processing Engineering)',
      'Bachelor Of Science (Mobile Telecommunications And Networking)',
      'Bachelor Of Science (Nautical Science)',
      'Bachelor Of Science (Nautical Science)',
      'Bachelor Of Science (Nursing And Public Health)',
      'Bachelor Of Science (Nursing)',
      'Bachelor Of Science (Nursing)',
      'Bachelor Of Science (Nursing)',
      'Bachelor Of Science (Nutrition And Dietetics)',
      'Bachelor Of Science (Nursing)',
      'Bachelor Of Science (Occupational Safety And Health)',
      'Bachelor Of Science (Oil And Gas Management)',
      'Bachelor Of Science (Oil And Gas Management)',
      'Bachelor Of Science (Oil, Energy And Gas Management)',
      'Bachelor Of Science (Oil, Gas And Energy Management)',
      'Bachelor Of Science (Operations Research)',
      'Bachelor Of Science (Optometry)',
      'Bachelor Of Science (Physics)',
      'Bachelor Of Science (Political Science And Public Administration)',
      'Bachelor Of Science (Public Health)',
      'Bachelor Of Science (Quantity Surveying)',
      'Bachelor Of Science (Quantity Surveying)',
      'Bachelor Of Science (Real Estate)',
      'Bachelor Of Science (Records Management)',
      'Bachelor Of Science (Renewable Energy And Environmental Physics)',
      'Bachelor Of Science (Renewable Energy Technology)',
      'Bachelor Of Science (Resource And Environmental Geology)',
      'Bachelor Of Science (Resource Economics)',
      'Bachelor Of Science (Resource Management)',
      'Bachelor Of Science (Resource Management)',
      'Bachelor Of Science (Resource Management)',
      'Bachelor Of Science (Social Work)',
      'Bachelor Of Science (Sociology And Anthropology)',
      'Bachelor Of Science (Software Engineering)',
      'Bachelor Of Science (Software Engineering)',
      'Bachelor Of Science (Software Engineering, With It)',
      'Bachelor Of Science (Software Engineering)',
      'Bachelor Of Science (Soil, Water And Environmental Engineering)',
      'Bachelor Of Science (Statistics)',
      'Bachelor Of Science (Statistics)',
      'Bachelor Of Science (Surveying And Geomatics)',
      'Bachelor Of Science (Sustainable Energy And Environmental Management)',
      'Bachelor Of Science (Telecommunications And Information Technology)',
      'Bachelor Of Science (Telecommunications And Information Technology)',
      'Bachelor Of Science (Tourism Management)',
      'Bachelor Of Science (Tourism Management)',
      'Bachelor Of Science (Tourism)',
      'Bachelor Of Science (Tourism)',
      'Bachelor Of Science (Tourism)',
      'Bachelor Of Science (Tourism)',
      'Bachelor Of Science (Travel And Tourism Management)',
      'Bachelor Of Science (Water And Environmental Engineering)',
      'Bachelor Of Science (Web Design And Development)',
      'Bachelor Of Science (Wildlife Management)',
      'Bachelor Of Science (Wildlife Management)',
      'Bachelor Of Science (Wildlife Management)',
      'Bachelor Of Science (Wildlife Management)',
      'Bachelor Of Science (Zoology)',
      'Bachelor Of Science (Zoology, With It)',
      'Bachelor Of Science Actuarial Science',
      'Bachelor Of Science Agricultural Economics',
      'Bachelor Of Science Agricultural Education',
      'Bachelor Of Science Agriculture',
      'Bachelor Of Science Agriculture And Biotechnology',
      'Bachelor Of Science Agriculture Education',
      'Bachelor Of Science Agroforestry',
      'Bachelor Of Science Animal Health',
      'Bachelor Of Science Animal Health And Production',
      'Bachelor Of Science Animal Production',
      'Bachelor Of Science Animation And Game Development',
      'Bachelor Of Science Animation And Multimedia Technology',
      'Bachelor Of Science Animation Production',
      'Bachelor Of Science Applied Analytical Chemistry',
      'Bachelor Of Science Applied Computer Science',
      'Bachelor Of Science Applied Computer Science',
      'Bachelor Of Science Applied Computer Science',
      'Bachelor Of Science Applied Physics',
      'Bachelor Of Science Applied Physics',
      'Bachelor Of Science Applied Statistics',
      'Bachelor Of Science Applied Zoology',
      'Bachelor Of Science Architecture',
      'Bachelor Of Science Biochemistry',
      'Bachelor Of Science Biochemistry',
      'Bachelor Of Science Bioinformatics',
      'Bachelor Of Science Biological Science',
      'Bachelor Of Science Biology',
      'Bachelor Of Science Biomedical Science',
      'Bachelor Of Science Biotechnology',
      'Bachelor Of Science Botany',
      'Bachelor Of Science Business & Information Technology',
      'Bachelor Of Science Business Administration',
      'Bachelor Of Science Business And Information Technology',
      'Bachelor Of Science Business Information Technology',
      'Bachelor Of Science Chemical And Process Engineering',
      'Bachelor Of Science Chemical Engineering',
      'Bachelor Of Science Chemistry',
      'Bachelor Of Science Civil & Structural Engineering',
      'Bachelor Of Science Civil And Structural Engineering',
      'Bachelor Of Science Civil Engineering',
      'Bachelor Of Science Clinical Medicine',
      'Bachelor Of Science Communication & Media Technology',
      'Bachelor Of Science Community Development',
      'Bachelor Of Science Computer Science',
      'Bachelor Of Science Computer Science',
      'Bachelor Of Science Computer Science',
      'Bachelor Of Science Computer Security And Forensics',
      'Bachelor Of Science Computer Technology',
      'Bachelor Of Science Conservation Biology',
      'Bachelor Of Science Counselling Psychology',
      'Bachelor Of Science Criminology & Penology',
      'Bachelor Of Science Criminology & Security Studies',
      'Bachelor Of Science Criminology And Penology',
      'Bachelor Of Science Criminology And Security Studies',
      'Bachelor Of Science Criminology, Criminal Justice And Public Safety',
      'Bachelor Of Science Criminology',
      'Bachelor Of Science Crop Science',
      'Bachelor Of Science Data Science',
      'Bachelor Of Science Data Science',
      'Bachelor Of Science Design',
      'Bachelor Of Science Diagnostic Radiography And Imaging',
      'Bachelor Of Science Disaster Management',
      'Bachelor Of Science Disaster Management',
      'Bachelor Of Science Economics & Finance',
      'Bachelor Of Science Economics & Mathematics',
      'Bachelor Of Science Economics And Finance',
      'Bachelor Of Science Economics And Finance',
      'Bachelor Of Science Economics And Finance',
      'Bachelor Of Science Economics',
      'Bachelor Of Science Economics',
      'Bachelor Of Science Economics, With It',
      'Bachelor Of Science Electrical & Electronics Engineering',
      'Bachelor Of Science Electrical And Electronics Engineering',
      'Bachelor Of Science Electronic & Computer Engineering',
      'Bachelor Of Science Electronic And Computer Engineering',
      'Bachelor Of Science Energy And Environmental Technology',
      'Bachelor Of Science Environmental Health',
      'Bachelor Of Science Environmental Management',
      'Bachelor Of Science Environmental Planning',
      'Bachelor Of Science Environmental Resource Conservation',
      'Bachelor Of Science Environmental Science',
      'Bachelor Of Science Environmental Studies',
      'Bachelor Of Science Environmental Studies',
      'Bachelor Of Science Environmental Studies',
      'Bachelor Of Science Environmental Studies',
      'Bachelor Of Science Environmental, Water And Natural Resources Management',
      'Bachelor Of Science Epidemiology And Biostatistics',
      'Bachelor Of Science Fashion Design',
      'Bachelor Of Science Fashion Design',
      'Bachelor Of Science Fashion Design',
      'Bachelor Of Science Fashion Design',
      'Bachelor Of Science Fashion Merchandising',
    ],
  },
];
