export const unis:any = [
  'Africa International University',
  'African Institute Of Research Development Studies',
  'Air Travel And Related Studies',
  'Alupe University College',
  'Bandari College',
  'Baraton University',
  'Beacon Technical Training Institute',
  'Bomet University College',
  'Bondo Technical Training Institute',
  'Bumbe Technical Training Institute',
  'Bureti Technical Training Institute',
  'Catholic University Of Eastern Africa',
  'Chuka Technical And Vocational College',
  'Chuka University',
  'Coast Institute Of Technology',
  'Co-Operative University College Of Kenya',
  'Daystar University',
  'Dedan Kimathi University',
  'East Africa Institute Of Certified Studies',
  'Egerton University',
  'Eldoret National Polytechnic',
  'Eldoret Technical Training Institute',
  'Embu College Of Professional Studies',
  'Embu University',
  'Godoma Technical Training Institute',
  'Gretsa University',
  'Institute Of Energy Studies And Research',
  'Jaramogi Oginga Odinga University',
  'Jomo Kenyatta University',
  'Kabarak University',
  'Kabete National Polytechnic',
  'Kabianga University',
  'Kaiboi Technical Training Institute',
  'Kaimosi College Of Research And Technology',
  'Karatina University',
  'Karen Technical Training Institute For The Deaf',
  'Kasarani Technical And Vocational College',
  'Katine Technical Training Institute',
  'KCA University',
  'Kenya Aeronautical College',
  'Kenya Assemblies Of God University',
  'Kenya Coast National Polytechnic',
  'Kenya Highlands University',
  'Kenya Institute Of Business And Counselling Studies(Kibco)',
  'Kenya Institute Of Highways And Building Technology',
  'Kenya Institute Of Management-Nanyuki Campus',
  'Kenya Institute Of Mass Communication',
  'Kenya Institute Of Special Education',
  'Kenya Institute Of Survey And Mapping',
  'Kenya Medical Training College - Garissa Campus',
  'Kenya Medical Training College - Kabarnet Campus',
  'Kenya Medical Training College - Kapenguria Campus',
  'Kenya Medical Training College - Kilifi Campus',
  'Kenya Medical Training College - Kisii Campus',
  'Kenya Medical Training College - Kuria Campus',
  'Kenya Medical Training College - Lodwar Campus',
  'Kenya Medical Training College - Makindu',
  'Kenya Medical Training College - Makueni Campus',
  'Kenya Medical Training College - Meru Campus',
  'Kenya Medical Training College - Mosoriot Campus',
  'Kenya Medical Training College - Nairobi Campus',
  'Kenya Medical Training College - Nyandarua Campus',
  'Kenya Medical Training College - Nyeri Campus',
  'Kenya Medical Training College-Kakamega Campus',
  'Kenya Medical Training College-Nairobi Campus',
  'Kenya Medical Training Institute - Eldoret Campus',
  'Kenya Medical Training Institute - Embu Campus',
  'Kenya Medical Training Institute - Kitui Campus',
  'Kenya Medical Training Institute - Loitoktok Campus',
  'Kenya Medical Training Institute - Msambweni Campus',
  'Kenya Medical Training Institute - Muranga Campus',
  'Kenya Medical Training Institute - Mwingi Campus',
  'Kenya Medical Training Institute - Thika Campus',
  'Kenya Methodist University',
  'Kenya Technical Trainers College',
  'Kenya Water Institute',
  'Kenya Wildlife Service',
  'Kenyatta University',
  'Kiambu Institute Of Science And Technology',
  'Kibabii Diploma Teachers Training College',
  'Kibabii University',
  'Kibwezi Teachers Training College',
  'Kilimambogo Highway Building And Technology',
  'Kirinyaga University',
  'Kiriri Women University',
  'Kisii National Polytechnic',
  'Kisii University',
  'Kisiwa Technical Training Institute',
  'Kisumu National Polytechnic',
  'Kitale National Polytechnic',
  'Laikipia University',
  'Maa Institute Of Professional Astudies',
  'Maasai Mara Technical And Vocational Training College',
  'Maasai Mara University',
  'Maasai Technical Training Institute',
  'Machakos Teachers College',
  'Machakos University',
  'Masai Technical Training Institute',
  'Maseno University',
  'Masinde Muliro University',
  'Mawego Technical Training Institute',
  'Meru National Polytechnic',
  'Meru University',
  'Michuki Technical Training Institute',
  'Miramar International College',
  'Moi Teaching And Referral Hospital College Of Health Sciences',
  'Moi University',
  'Mombasa Technical University',
  'Mount Kenya University',
  'Mukurweini Technical Training Institute',
  'Multimedia University',
  'Muranga University Of Technology',
  'Nairobi Institute Of Business Studies',
  'Nairobi Technical Training Institute',
  'Nairobi University',
  'National Industrial Training Authority (Nita)',
  'Nkabune Technical Training Institute',
  'North Eastern National Polytechnic (Nep)',
  'Nyandarua Institute Of Science And Technology',
  'Nyeri National Polytechnic',
  'O’Lessoss Technical Training Institute',
  'Open University of Kenya',
  'Pc Kinyanjui Technical Training Institute',
  'Pioneer University',
  'Pwani University',
  'Railways Training Institute',
  'Ramogi Institute Of Advanced Technology',
  'Ramogi Institute Of Science And Technology',
  'Regional Center For Mapping Of Resources For Development',
  'Riara University',
  'Rift Valley Institute Of Science And Technology',
  'Rift Valley Technical Training Institute',
  'Riftvalley Institute Of Science & Technology',
  'Rongo University',
  'SangAlo Institute Of Science And Technology',
  'Scott Christian University',
  'Shamberere Technical Training Institute',
  'Siaya Institute Of Technology',
  'Sigalagala National Polytechnic',
  'Sister Leonella Consolata Medical College',
  'Sot Technical Training Institute',
  'South Eastern Kenya University',
  'St. Paul University',
  'Strathmore University',
  'Taita Taveta University',
  'Tangaza University',
  'Technical University Of Kenya',
  'The Aga Khan University',
  'The Kenya Coast National Polytechnic',
  'The Kenya Institute Of Management-Thika Campus',
  'Thika Institute Of Business Studies',
  'Thika School Of Medical And Health Sciences',
  'Thika Technical Training Institute',
  'Tom Mboya University College',
  'Tseikuru Technical Training Institute',
  'Turkana University College',
  'Ugenya Training Vocational Institute Of Technology',
  'Ukunda Vocational Training Center',
  'Ummah University',
  'United States International University',
  'University Of Eldoret',
  'Uzima University College',
  'Vera Beaury And Fashion College-Eldoret',
  'Vera Beauty And Fashion College-Nairobi',
  'Vera Beauty And Fashion College-Nakuru',
  'Vera Beauty And Fashion College-Thika',
  'Wote Technical Training Institute',
  'Zetech University',
];
